### PR TITLE
Rendering Lucille gif into Rmarkdown

### PR DESCRIPTION
**Pull request by setgree**
Up there with mistaking the "“drowsy eye” alcohol warning for a “winking-eye” alcohol suggestion" as one of the show's best visual jokes.

Thank you Lucy McGowan et al. for the package!

### CODE REVIEW

**Comment by LucyMcGowan** [comment]
lovely, thank you @setgree! Looks 💃 - Can you run the .Rmd file one more time to update the .md file as well? 🎉 I think the last commit removes the changes from the .md file.

**Comment by setgree** [comment]
Oh my mistake, I thought you wanted the gif *out of md file. I'll put it back in.

**Comment by LucyMcGowan** [comment]
Ah sorry miscommunication! We make all of the changes for the README in the .Rmd file and then render it to create the .md file (so both end up getting updated, but the .Rmd file is the only one that is *manually* changed).

**Comment by LucyMcGowan** [comment]
Merged - thank you @setgree! :tada:

**Comment by setgree** [comment]
Oh well thank you! You can ignore my next pull request then, it was exactly the same thing except I actually knit the readme in Rstudio.

**Comment by LucyMcGowan** [comment]
Ah yes! That was what I meant above -- sorry about the confusion! Thanks for the PR!

**Pull request merged**
